### ISSUE TITLE
Some imported tweets appear as recent

### ISSUE THREAD

**Issue by ssg** [marcomaroni-github/twitter-to-bluesky#97]
Several tweets from 2014 have appeared on my timeline as recent posts (e.g. 32s, 2m old). It's the minority but quite bothering for my followers. How can I prevent this from happening? That's pretty much the minority of tweets but still problematic.

**Comment by ssg** [comment]
An example post: https://bsky.app/profile/ssg.dev/post/3lbdmgs4xgo2x

Actual import log:

```
Parse tweet id '471621959688933376'
 Created at 2014-05-28T12:00:12.000Z
 Full text 'artwork kitabı çok özenli hazırlanmış @MonochromaGame http://t.co/YSEa1ixM6o'
{
  '$type': 'app.bsky.feed.post',
  text: 'artwork kitabı çok özenli hazırlanmış @MonochromaGame',
  facets: undefined,
  createdAt: '2014-05-28T12:00:12.000Z',
  embed: { '$type': 'app.bsky.embed.images', images: [ [Object] ] }
}
Bluesky post create, URL: https://bsky.app/profile/ssg.dev/post/3lbdmgs4xgo2x
```

**Comment by ssg** [comment]
Oh it seems like a BlueSky feed bug. The date got itself fixed after a while. Closing this.

**Comment by jbilbo** [comment]
Did Bluesky changed the way to show the timestamp in the timeline? All my imported posts are showed in the correct order in the timeline but with the recent timestamp instead of the original date.  cc: @marcomaroni-github 
We can see what I mean in the example @ssg put above, and the original date is displayed as "archived from" with this warning message:

![Screenshot 2024-11-23 at 03 51 54](https://github.com/user-attachments/assets/cfdb3b8f-93cc-44dd-97fd-04a20baaaf6e)


![Screenshot 2024-11-23 at 03 50 40](https://github.com/user-attachments/assets/fd152695-869a-48da-9498-3f74d66f65d4)

**Comment by marcomaroni-github** [comment]
Hi @jbilbo I had read something about this and I fear that the changes are now effective, it is a permanent change they made to highlight posts created in the past.
